name = "Working_With_Data"
uuid = "4a8d05d6-b0c5-43e3-a15e-8b0006e8cfc3"
authors = ["Paul Kussner paul.kuessner@student.uibk.ac.at"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
julia = "1.11.7"
